

CREATE TABLE Localidades(
  cp SERIAL NOT NULL PRIMARY KEY,
  nombre_localidad VARCHAR(20) NOT NULL
);

INSERT INTO LOCALIDADES (CP, NOMBRE_LOCALIDAD) VALUES ('5500','CIUDAD');
INSERT INTO LOCALIDADES (CP, NOMBRE_LOCALIDAD) VALUES ('5501','GODOY CRUZ');
INSERT INTO LOCALIDADES (CP, NOMBRE_LOCALIDAD) VALUES ('5539','LAS HERAS');
INSERT INTO LOCALIDADES (CP, NOMBRE_LOCALIDAD) VALUES ('5521','GUAYMALLEN');

SELECT * FROM Localidades;

CREATE TABLE IF NOT EXISTS Personas_NEW (
    dni SERIAL NOT NULL PRIMARY KEY,
    apellido VARCHAR(15) NOT NULL,
    nombre VARCHAR(15) NOT NULL,
    edad INTEGER NOT NULL,
	domicilio VARCHAR(20) NOT NULL,
    cp INTEGER NOT NULL,
    CONSTRAINT fk_cp
        FOREIGN KEY (cp) -- Se define la clave foránea
        REFERENCES Localidades (cp) -- Se referencia la columna cp de la tabla Localidades
);

INSERT INTO PERSONAS_NEW (DNI,APELLIDO,NOMBRE,EDAD,DOMICILIO,CP) VALUES ('30000000','AGUERO','JAVIER','32','DR MORENO 123','5539');
INSERT INTO PERSONAS_NEW (DNI,APELLIDO,NOMBRE,EDAD,DOMICILIO,CP) VALUES ('31000000','BOTTA','LAURA','32','DAMIAN HUDSON 258','5500');
INSERT INTO PERSONAS_NEW (DNI,APELLIDO,NOMBRE,EDAD,DOMICILIO,CP) VALUES ('35000000','CASTILLO','ANGELA','25','ADOLFO CALLE 3526','5521');
INSERT INTO PERSONAS_NEW (DNI,APELLIDO,NOMBRE,EDAD,DOMICILIO,CP) VALUES ('20000000','GUTIERREZ','ALBERTO','50','LAVALLE 552','5501');
INSERT INTO PERSONAS_NEW (DNI,APELLIDO,NOMBRE,EDAD,DOMICILIO,CP) VALUES ('33000000','HONORATO','MARIA','28','ALPATACAL 3254','5500');
INSERT INTO PERSONAS_NEW (DNI,APELLIDO,NOMBRE,EDAD,DOMICILIO,CP) VALUES ('38000000','JUAREZ','MONICA','22','DR MORENO 695','5539');
INSERT INTO PERSONAS_NEW (DNI,APELLIDO,NOMBRE,EDAD,DOMICILIO,CP) VALUES ('37000000','KOLMAN','PATRICIA','24','HOUSAY 223','5521');
INSERT INTO PERSONAS_NEW (DNI,APELLIDO,NOMBRE,EDAD,DOMICILIO,CP) VALUES ('32000000','LOPEZ','JAVIER','30','ARIZU 691','5501');
INSERT INTO PERSONAS_NEW (DNI,APELLIDO,NOMBRE,EDAD,DOMICILIO,CP) VALUES ('36000000','MANRIQUE','ESTELA','25','JORGE A CALLE 321','5500');
INSERT INTO PERSONAS_NEW (DNI,APELLIDO,NOMBRE,EDAD,DOMICILIO,CP) VALUES ('29000000','AGUERO','JAVIER','34','RIVADAVIA 549','5539');


SELECT * FROM Personas_NEW;


-- 1
SELECT DNI,APELLIDO,NOMBRE,DOMICILIO,NOMBRE_LOCALIDAD FROM Localidades
INNER JOIN Personas_NEW ON Localidades.cp = Personas_NEW.cp;

-- 2
SELECT Nombre_Localidad, COUNT(*) AS "Cantidad_Personas" FROM Localidades
INNER JOIN Personas_NEW ON Localidades.cp = Personas_NEW.cp
GROUP BY Nombre_Localidad;
	
