

CREATE TABLE IF NOT EXISTS EMPLEADOS (
    DNI SERIAL PRIMARY KEY,
    APELLIDO VARCHAR(15),
    NOMBRE VARCHAR(15),
    FECHA_NAC DATE,
    SEXO VARCHAR(24),
    CARGO VARCHAR(20),
    SALARIO INTEGER
);

INSERT INTO EMPLEADOS (DNI, APELLIDO, NOMBRE, FECHA_NAC, SEXO, CARGO, SALARIO) VALUES (32458745, 'GONZALEZ', 'NATALIA', '1987-04-25', 'F', 'ADMINISTRATIVO', 15000);
INSERT INTO EMPLEADOS (DNI, APELLIDO, NOMBRE, FECHA_NAC, SEXO, CARGO, SALARIO) VALUES (35689421, 'GOMEZ', 'LARA', '1990-01-12', 'F', 'JEFE_AREA', 30000);
INSERT INTO EMPLEADOS (DNI, APELLIDO, NOMBRE, FECHA_NAC, SEXO, CARGO, SALARIO) VALUES (29548722, 'ARAUJO', 'MATIAS', '1984-07-17', 'M', 'OFICIAL', 24500);
INSERT INTO EMPLEADOS (DNI, APELLIDO, NOMBRE, FECHA_NAC, SEXO, CARGO, SALARIO) VALUES (28555487, 'MARTINEZ', 'MARCOS', '1982-01-04', 'M', 'GERENTE', 35000);
INSERT INTO EMPLEADOS (DNI, APELLIDO, NOMBRE, FECHA_NAC, SEXO, CARGO, SALARIO) VALUES (35552237, 'RODRIGUEZ', 'MONICA', '1989-08-30', 'F', 'ADMINISTRATIVO', 18000);
INSERT INTO EMPLEADOS (DNI, APELLIDO, NOMBRE, FECHA_NAC, SEXO, CARGO, SALARIO) VALUES (36989147, 'GOMEZ', 'RICARDO', '1991-12-25', 'M', 'ADMINISTRATIVO', 18000);
INSERT INTO EMPLEADOS (DNI, APELLIDO, NOMBRE, FECHA_NAC, SEXO, CARGO, SALARIO) VALUES (24232436, 'VALLES', 'RAQUEL', '1975-04-10', 'F', 'CELADOR', 12000);
INSERT INTO EMPLEADOS (DNI, APELLIDO, NOMBRE, FECHA_NAC, SEXO, CARGO, SALARIO) VALUES (28556921, 'VAZQUEZ', 'NORMA', '1982-08-21', 'F', 'OFICIAL', 22000);


SELECT * FROM EMPLEADOS;

-- 1
SELECT COUNT(CARGO) FROM EMPLEADOS
WHERE CARGO = 'ADMINISTRATIVO';

-- 2

SELECT COUNT (CARGO) FROM EMPLEADOS
WHERE CARGO = 'ADMINISTRATIVO' AND SEXO = 'F';

-- 3

SELECT SEXO, COUNT(*) AS TOTAL
FROM EMPLEADOS
GROUP BY SEXO;

-- 4

SELECT SEXO, COUNT(*) AS MAYOR_18000
FROM EMPLEADOS
WHERE SALARIO > 18000
GROUP BY SEXO;

-- 5

SELECT SEXO, AVG(SALARIO) AS PROMEDIO
FROM EMPLEADOS
GROUP BY SEXO;

-- 6

SELECT SEXO, COUNT(*)
FROM EMPLEADOS
WHERE FECHA_NAC > '1982-1-1'
GROUP BY SEXO;
